// Cartas de La Previa. {A} y {B} son jugadores al azar. {T} son tragos (o flexiones en modo sin alcohol).
var CARTAS = {
  nunca: [
    'Yo nunca he stalkeado a un ex en Instagram',
    'Yo nunca me he dormido en el transporte público y me he pasado de parada',
    'Yo nunca he fingido estar enfermo para no ir a clase o al trabajo',
    'Yo nunca he mandado un audio de más de cinco minutos',
    'Yo nunca he dicho "estoy llegando" sin haber salido de casa',
    'Yo nunca he leído los mensajes de otra persona sin permiso',
    'Yo nunca he llorado viendo una película de dibujos',
    'Yo nunca he mentido sobre mi edad',
    'Yo nunca me he enamorado de alguien de este grupo',
    'Yo nunca he hecho ghosting',
    'Yo nunca he usado la cuenta de Netflix de un ex',
    'Yo nunca he cantado en la ducha como si fuera un concierto',
    'Yo nunca he comido algo que se había caído al suelo',
    'Yo nunca he fingido que me gustaba un regalo',
    'Yo nunca me he colado en un sitio sin pagar',
    'Yo nunca he dado like sin querer a una foto antigua',
    'Yo nunca he mandado un mensaje a la persona equivocada',
    'Yo nunca he tenido una cuenta secundaria en redes',
    'Yo nunca he suspendido un examen de conducir',
    'Yo nunca he mentido en este juego',
    'Yo nunca me he quedado dormido en una fiesta',
    'Yo nunca he roto algo y he culpado a otro',
    'Yo nunca he tenido un crush con un profesor',
    'Yo nunca he hablado mal de alguien que está aquí',
    'Yo nunca he buscado mi propio nombre en Google',
    'Yo nunca he pedido comida a domicilio dos veces el mismo día',
    'Yo nunca he dejado a alguien en visto a propósito',
    'Yo nunca he bailado solo delante del espejo',
    'Yo nunca he olvidado el cumpleaños de mi mejor amigo',
    'Yo nunca he tenido miedo a la oscuridad siendo adulto'
  ],
  probable: [
    '¿Quién es más probable que acabe siendo famoso?',
    '¿Quién es más probable que se case primero?',
    '¿Quién es más probable que pierda el móvil esta noche?',
    '¿Quién es más probable que sobreviva a un apocalipsis zombi?',
    '¿Quién es más probable que llegue tarde a su propia boda?',
    '¿Quién es más probable que se haga viral en TikTok?',
    '¿Quién es más probable que se duerma primero hoy?',
    '¿Quién es más probable que acabe viviendo en otro país?',
    '¿Quién es más probable que le escriba a su ex esta noche?',
    '¿Quién es más probable que gane la lotería y lo pierda todo?',
    '¿Quién es más probable que se ría en un funeral?',
    '¿Quién es más probable que se apunte a un reality?',
    '¿Quién es más probable que tenga diez gatos?',
    '¿Quién es más probable que se pierda con el GPS puesto?',
    '¿Quién es más probable que acabe en la cárcel por una tontería?',
    '¿Quién es más probable que monte una empresa?',
    '¿Quién es más probable que se olvide de dónde ha aparcado?',
    '¿Quién es más probable que coma pizza con piña?',
    '¿Quién es más probable que se haga un tatuaje del que se arrepienta?',
    '¿Quién es más probable que conteste un mensaje a los tres días?'
  ],
  reto: [
    '{A}, imita a {B} hasta que alguien lo adivine. Si nadie lo adivina, {T}',
    '{A}, enseña la última foto de tu galería o {T}',
    '{A}, habla con acento argentino hasta tu próximo turno',
    '{A} y {B}, piedra, papel o tijera. Quien pierda, {T}',
    '{A}, deja que {B} te escriba un estado de WhatsApp o {T}',
    '{A}, di tres cosas buenas de {B} sin repetir',
    'Todos los que lleven algo negro, {T}',
    '{A}, cuenta tu peor cita en treinta segundos o {T}',
    '{A}, nombra cinco marcas de cerveza en diez segundos o {T}',
    'Cascada: empieza {A} y nadie para hasta que pare quien tiene a su derecha',
    '{A}, elige a alguien para que {T} contigo',
    '{A}, haz una declaración de amor dramática a {B}',
    'El último en tocarse la nariz, {T}',
    '{A}, canta el estribillo de una canción que elija {B}',
    '{A}, lee en voz alta tu último mensaje enviado o {T}',
    'Categorías, empieza {A}: equipos de fútbol españoles. El que falle, {T}',
    'Categorías, empieza {A}: series de Netflix. El que falle, {T}',
    'Categorías, empieza {A}: pueblos de España. El que falle, {T}',
    '{A}, hasta tu siguiente turno no puedes decir "sí" ni "no". Cada vez que falles, {T}',
    '{A}, intercambia el sitio con {B}',
    'Los que tengan hermanos, {T}',
    '{A}, ponle un mote a cada jugador. Se queda toda la partida',
    'El más alto del grupo reparte {T} como quiera',
    '{A}, cuenta un chiste. Si nadie se ríe, {T}',
    '{A} y {B}, duelo de miradas. El que se ría primero, {T}'
  ],
  verdad: [
    '{A}, ¿qué es lo más vergonzoso que has buscado en Google?',
    '{A}, ¿a quién de aquí llamarías a las 4 de la mañana?',
    '{A}, ¿cuál es tu mayor miedo absurdo?',
    '{A}, ¿qué es lo más caro que has roto?',
    '{A}, ¿qué opinas de verdad del outfit de {B}?',
    '{A}, ¿cuál ha sido tu peor nota y en qué?',
    '{A}, ¿a quién de aquí cambiarías la vida por un día?',
    '{A}, ¿cuál es tu canción vergonzosa favorita?',
    '{A}, ¿qué mentira has contado esta semana?',
    '{A}, ¿cuál es la cosa más rara que has comido?',
    '{A}, ¿qué le dirías a tu yo de hace cinco años?',
    '{A}, ¿cuál es tu red flag?',
    '{A}, ¿qué primera impresión te dio {B}?',
    '{A}, ¿qué app te da vergüenza tener instalada?',
    '{A}, ¿cuál es el último cotilleo que te han contado? Sin nombres'
  ]
};
